//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Hex.Migration.Toolkit.Portal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Hex.Migration.Toolkit.Portal.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the rights needed to access this area.
        /// </summary>
        public static string AccessDeniedMessage {
            get {
                return ResourceManager.GetString("AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string AddCapital {
            get {
                return ResourceManager.GetString("AddCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddCaption {
            get {
                return ResourceManager.GetString("AddCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mailboxes.
        /// </summary>
        public static string AddMailboxes {
            get {
                return ResourceManager.GetString("AddMailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new migration batch.
        /// </summary>
        public static string AddMigrationBatch {
            get {
                return ResourceManager.GetString("AddMigrationBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new environment.
        /// </summary>
        public static string AddNewEnvironment {
            get {
                return ResourceManager.GetString("AddNewEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an input error encountered. Please check the inputs and try again..
        /// </summary>
        public static string BadInputGenericMessage {
            get {
                return ResourceManager.GetString("BadInputGenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created batch.
        /// </summary>
        public static string BatchRegistrationSuccessMessage {
            get {
                return ResourceManager.GetString("BatchRegistrationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this environment?.
        /// </summary>
        public static string DeleteEnvrionmentMessage {
            get {
                return ResourceManager.GetString("DeleteEnvrionmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting environment....
        /// </summary>
        public static string DeletingEnvironmentMessage {
            get {
                return ResourceManager.GetString("DeletingEnvironmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting migration batch....
        /// </summary>
        public static string DeletingMigrationBatchMessage {
            get {
                return ResourceManager.GetString("DeletingMigrationBatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to process your request at this time. Please try later or contact support..
        /// </summary>
        public static string DownstreamErrorPrefix {
            get {
                return ResourceManager.GetString("DownstreamErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string Ellipsis {
            get {
                return ResourceManager.GetString("Ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a mailbox.
        /// </summary>
        public static string EmptyListCaption {
            get {
                return ResourceManager.GetString("EmptyListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entities found.
        /// </summary>
        public static string EmptyListMessage {
            get {
                return ResourceManager.GetString("EmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one mailbox.
        /// </summary>
        public static string EmptyMailboxesErrorMessage {
            get {
                return ResourceManager.GetString("EmptyMailboxesErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        public static string Endpoint {
            get {
                return ResourceManager.GetString("Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the specified entity or the user is not authorized to perform this operation..
        /// </summary>
        public static string EntityNotFoundException {
            get {
                return ResourceManager.GetString("EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Email Address.
        /// </summary>
        public static string EnvironmentAdminEmail {
            get {
                return ResourceManager.GetString("EnvironmentAdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment and associated mailboxes have been deleted.
        /// </summary>
        public static string EnvironmentDeletionConfirmation {
            get {
                return ResourceManager.GetString("EnvironmentDeletionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete the environment....
        /// </summary>
        public static string EnvironmentDeletionFailure {
            get {
                return ResourceManager.GetString("EnvironmentDeletionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        public static string EnvironmentEndpointCaption {
            get {
                return ResourceManager.GetString("EnvironmentEndpointCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint address for the Exchange environment. The address should look like https://webmail.fabrikam.com/PowerShell.
        /// </summary>
        public static string EnvironmentEndpointInfoCaption {
            get {
                return ResourceManager.GetString("EnvironmentEndpointInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Information.
        /// </summary>
        public static string EnvironmentInfoSectionCaption {
            get {
                return ResourceManager.GetString("EnvironmentInfoSectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EnvironmentNameCaption {
            get {
                return ResourceManager.GetString("EnvironmentNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The friendly name for the environment. This value is only utilized by this portal..
        /// </summary>
        public static string EnvironmentNameInfoCaption {
            get {
                return ResourceManager.GetString("EnvironmentNameInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string EnvironmentPasswordCaption {
            get {
                return ResourceManager.GetString("EnvironmentPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment was successfully refreshed..
        /// </summary>
        public static string EnvironmentRefreshConfirmation {
            get {
                return ResourceManager.GetString("EnvironmentRefreshConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not refresh the environment....
        /// </summary>
        public static string EnvironmentRefreshFailure {
            get {
                return ResourceManager.GetString("EnvironmentRefreshFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing environment.
        /// </summary>
        public static string EnvironmentRefreshingMessage {
            get {
                return ResourceManager.GetString("EnvironmentRefreshingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering environment....
        /// </summary>
        public static string EnvironmentRegistrationMessage {
            get {
                return ResourceManager.GetString("EnvironmentRegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created environment.
        /// </summary>
        public static string EnvironmentRegistrationSuccessMessage {
            get {
                return ResourceManager.GetString("EnvironmentRegistrationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve environments....
        /// </summary>
        public static string EnvironmentRetrievalFailure {
            get {
                return ResourceManager.GetString("EnvironmentRetrievalFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environments.
        /// </summary>
        public static string EnvironmentsTableSection {
            get {
                return ResourceManager.GetString("EnvironmentsTableSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string EnvironmentUsernameCaption {
            get {
                return ResourceManager.GetString("EnvironmentUsernameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the administrative username, in admin@fabrikam.com format, for the hosted instance of Exchange..
        /// </summary>
        public static string EnvironmentUsernameInfoCaption {
            get {
                return ResourceManager.GetString("EnvironmentUsernameInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get portal content.
        /// </summary>
        public static string FailedToLoadPortal {
            get {
                return ResourceManager.GetString("FailedToLoadPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Name.
        /// </summary>
        public static string FriendlyName {
            get {
                return ResourceManager.GetString("FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents.
        /// </summary>
        public static string Incidents {
            get {
                return ResourceManager.GetString("Incidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid address.
        /// </summary>
        public static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem in one of the fields you entered:.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the invalid input:.
        /// </summary>
        public static string InvalidInputErrorPrefix {
            get {
                return ResourceManager.GetString("InvalidInputErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more fields are invalid. Please correct them and then submit..
        /// </summary>
        public static string InvalidInputInFormCaption {
            get {
                return ResourceManager.GetString("InvalidInputInFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal configuration seems to be invalid.
        /// </summary>
        public static string InvalidPortalConfiguration {
            get {
                return ResourceManager.GetString("InvalidPortalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft ID.
        /// </summary>
        public static string MicrosoftId {
            get {
                return ResourceManager.GetString("MicrosoftId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this migration batch?.
        /// </summary>
        public static string MigrationBatchDeleteMessage {
            get {
                return ResourceManager.GetString("MigrationBatchDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete the migration batch....
        /// </summary>
        public static string MigrationBatchDeletionFailure {
            get {
                return ResourceManager.GetString("MigrationBatchDeletionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Batches.
        /// </summary>
        public static string MigrationBatchesTableSection {
            get {
                return ResourceManager.GetString("MigrationBatchesTableSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Information.
        /// </summary>
        public static string MigrationBatchInfoSectionCaption {
            get {
                return ResourceManager.GetString("MigrationBatchInfoSectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MigrationBatchNameCaption {
            get {
                return ResourceManager.GetString("MigrationBatchNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string MigrationBatchStartTimeCaption {
            get {
                return ResourceManager.GetString("MigrationBatchStartTimeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Batch Information.
        /// </summary>
        public static string MigrationBatchTableSection {
            get {
                return ResourceManager.GetString("MigrationBatchTableSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The migration batch was successfully deleted..
        /// </summary>
        public static string MigrationDeletionConfirmation {
            get {
                return ResourceManager.GetString("MigrationDeletionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More actions....
        /// </summary>
        public static string MoreActionsTooltip {
            get {
                return ResourceManager.GetString("MoreActionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to:.
        /// </summary>
        public static string NavigateBackTo {
            get {
                return ResourceManager.GetString("NavigateBackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active notifications.
        /// </summary>
        public static string NotificationSectionTooltip {
            get {
                return ResourceManager.GetString("NotificationSectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new notifications.
        /// </summary>
        public static string NotificationsSummary {
            get {
                return ResourceManager.GetString("NotificationsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneHeaderCaption {
            get {
                return ResourceManager.GetString("PhoneHeaderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required..
        /// </summary>
        public static string PhoneHeaderRequired {
            get {
                return ResourceManager.GetString("PhoneHeaderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal configuation could not be found.
        /// </summary>
        public static string PortalConfigurationNotFound {
            get {
                return ResourceManager.GetString("PortalConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup the portal.
        /// </summary>
        public static string PortalSetupPromptMessage {
            get {
                return ResourceManager.GetString("PortalSetupPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing the migration batch....
        /// </summary>
        public static string PreparingBatchMessage {
            get {
                return ResourceManager.GetString("PreparingBatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing the order....
        /// </summary>
        public static string ProcessingOrder {
            get {
                return ResourceManager.GetString("ProcessingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX Migration Toolkit.
        /// </summary>
        public static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the specified instance..
        /// </summary>
        public static string RedisCacheConnectionException {
            get {
                return ResourceManager.GetString("RedisCacheConnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from batch.
        /// </summary>
        public static string RemoveFromBatch {
            get {
                return ResourceManager.GetString("RemoveFromBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETRY.
        /// </summary>
        public static string RetryCapital {
            get {
                return ResourceManager.GetString("RetryCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a mailbox.
        /// </summary>
        public static string SelectMailboxCaption {
            get {
                return ResourceManager.GetString("SelectMailboxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out from the application.
        /// </summary>
        public static string SignOutToolTipCaption {
            get {
                return ResourceManager.GetString("SignOutToolTipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Delivery Domain.
        /// </summary>
        public static string TargetDeliverDomain {
            get {
                return ResourceManager.GetString("TargetDeliverDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get the feature content.
        /// </summary>
        public static string TemplateLoadFailureMessage {
            get {
                return ResourceManager.GetString("TemplateLoadFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting feature content.
        /// </summary>
        public static string TemplateLoadRetryMessage {
            get {
                return ResourceManager.GetString("TemplateLoadRetryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Principal Name.
        /// </summary>
        public static string UserPrincipalName {
            get {
                return ResourceManager.GetString("UserPrincipalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authenticated user is not authorized to perform this operation..
        /// </summary>
        public static string UserUnauthorizedException {
            get {
                return ResourceManager.GetString("UserUnauthorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
